# Generated by Django 3.0.2 on 2020-01-28 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Pessoa',
        ),
    ]
